language: php
php:
- 5.5
- 5.4
- 5.3
- hhvm
matrix:
  fast_finish: true
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: SiJmgfXdqi8AyEbSvg/CEGyWBRIcpfRI04O+3eu5uP3S/gxAF/H/3CQJBVu1XHb7NiDnnBzabhaWz2aUE02Z/0PK6ZrkRfd5xUD7mISkRwiutLEKmuywwI2B/3QuRSfmMNu54SImsQNIxtvgHGYs5nr2TIDCzdfr/oTZrhtpH7M=
