language: php
php:
- 5.5
- 5.4
- 5.3
- hhvm
before_install:
  - npm install -g grunt-cli
  - composer install --dev --no-progress
install:
  - npm install
script:
  - grunt build
deploy:
  provider: heroku
  app: bootigniter
  on:
    php: 5.3
  api_key:
    secure: SiJmgfXdqi8AyEbSvg/CEGyWBRIcpfRI04O+3eu5uP3S/gxAF/H/3CQJBVu1XHb7NiDnnBzabhaWz2aUE02Z/0PK6ZrkRfd5xUD7mISkRwiutLEKmuywwI2B/3QuRSfmMNu54SImsQNIxtvgHGYs5nr2TIDCzdfr/oTZrhtpH7M=
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
branches:
  only:
  - master
