language: php
php:
- 5.5
- 5.4
- 5.3
- hhvm
before_install:
  - npm install -g grunt-cli
  - composer install --dev --no-progress
install:
  - npm install
script:
  - grunt phptest
matrix:
  fast_finish: true
branches:
  only:
  - master
